### ISSUE TITLE
Research Spike: Embassy for AMALTHEA

### ISSUE THREAD

**Issue by thelenlucas** [Terminus-Suborbital-Research-Program/AMALTHEA-Software-Systems#18]
Deliverable: Writeup in repository for this platform, plus any relevant UML or supplementary materials.

**Comment by supergoodname77** [comment]
[External Deliverable](https://docs.google.com/document/d/1nqtkSTgJkK1JWMCQein9IeYzA4PRX0rpPbxb6nO8RRw/edit?usp=sharing)
